# basic options
title: Mab's webpage
author: Mab Alam
email: email@domain.com
#description: Personal website
twitter_username: dataenthus
github_username:  mabsal

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-minimal
